export const mapShopifyToInvoiceData = (shopifyData: any): any => {
    return {
        Cliente: {
            NumeroDocumento: shopifyData.customer.id.toString(),
            PrimerApellido: shopifyData.billing_address.last_name,
            SegundoApellido: "",
            PrimerNombre: shopifyData.billing_address.first_name,
            SegundoNombre: "",
            Telefono: shopifyData.billing_address.phone || "",
            CodigoDaneCiudad: "11001",
            TipoRegimen: 0,
            Direccion: shopifyData.billing_address.address1,
            Email: shopifyData.email,
            TipoDocumento: 13,
            Naturaleza: 0,
            RegimenFiscalCodigo: "49",
            ResponsabilidadesFiscalesCodigo: "R-99-PN",
            TributosCodigo: "ZZ",
        },
        NumeroOrdenPedido: shopifyData.order_number.toString(),
        FormasPago: [
            {
                Codigo: 8,
                Valor: parseFloat(shopifyData.total_price),
                NumeroComprobante: shopifyData.order_number.toString(),
                TipoTarjetas: 0,
                CodigoFranquiciaTarjetas: 1,
                CodigoCuentaBancaria: 9,
            },
        ],
        Producto: shopifyData.line_items.map((item: any) => ({
            Referencia: item.id,
            CodigoBarras: item.sku || "000000000000",
            Cantidad: item.quantity,
            PrecioVentaConIva: parseFloat(item.price),
            PorcentajeIva: shopifyData.tax_lines[0]?.rate * 100 || 0,
            IdIva: 0,
            ValorBase: parseFloat(item.price),
            PorcentajeDescuento: 0,
            TotalDescuento: 0,
            ValorTotal: parseFloat(item.price),
            Combo: 0,
            CostoUnitario: 0,
        })),
        NumeroDocumentoEmpleado: "9999999",
        TipoNumeracion: 0,
        Token: shopifyData.token,
    };
};
